# Generated by Django 5.0.6 on 2024-11-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProperty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'organization_data',
            },
        ),
    ]
